### ISSUE TITLE
Version 3.0 do not change active button color

### ISSUE THREAD

**Issue by jescorotero** [erikwett/qsVariable#26]
Since we have installed the new 3.0 version, new qsVariable objects using Button (qlik, bootstrap,...) doesn't change to active color but action is executed properly.  Usually active option is green but now there is no green or only one, the first, but it not change to the active or selected option.

Newly created: there is not green option_:
![image](https://user-images.githubusercontent.com/1407874/27901464-7bd152d8-6232-11e7-9957-7d08a7818173.png)

Reusing (copy - paste) older objects: the first option always green:

![image](https://user-images.githubusercontent.com/1407874/27901521-b0c9b778-6232-11e7-9aa2-49c06b41bbfb.png)

**Comment by erikwett** [comment]
Fixed in version 3.0.1

**Comment by everythingiswrong** [comment]
This is still an issue for me with Qlik Sense June 2017 and the updated v3.0.1 of this extension.

**Comment by erikwett** [comment]
I'm afraid objects created with the 3.0.0 version will not work. You need to recreate objects with 3.0.1 (or it might be enough to update the varaible in the property panel, that is select another one and then back to the first one). Also make sure to refresh your browser cahce or run with caching turned off.

**Comment by everythingiswrong** [comment]
Have tried those suggestions without luck.

Created new objects with v3.0.1 of the extension. Disabled network cache in DevTools and refreshed. Verified in DevTools it is loading v3.0.1 of the extension. Tried in browser (with cache disabled). Tried creating new Qlik Sense apps, etc.

Also seeing an issue where for user-created variables, the existing value of the variable isn't being recognised by the extension (e.g. When rendering as a field the existing value would normally show)

Using Qlik Sense June 2017 on Windows 10 if that makes a difference.

**Comment by everythingiswrong** [comment]
Looks like it may be caused by variables with hyphens in the name. Without those it seems to work as expected.

**Comment by jescorotero** [comment]
We have followed @erikwett instructions and worked.  Even having "@1 - Stage A" labels with hyphens. Thanks

**Comment by everythingiswrong** [comment]
@jescorotero: The problem seems to be with hyphens in variable names rather than the labels.

Hyphens are permitted characters in Qlik variable names.

**Comment by everythingiswrong** [comment]
Row 58 in properties.js seems to cause the issue.

Adding escaped double quotation marks around data.variableName appears to resolve the issue for me.

I'm no JavaScript expert so there may be a more elegant solution!

**Comment by erikwett** [comment]
Added this escape in version 3.0.2. Note that the old version has no escape, so this probably does not work there.
